# Generated by Django 5.0.4 on 2024-04-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketShop', '0002_game_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='total_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
