# Generated by Django 5.0 on 2024-04-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_news_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Image',
            field=models.TextField(default='https://th.bing.com/th/id/R.daa7359bb5a739976f49f73a13248445?rik=96%2fTS%2buS%2fKFAyA&pid=ImgRaw&r=0'),
        ),
    ]
