# Generated by Django 5.0 on 2024-04-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
