# Generated by Django 5.0 on 2024-04-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_news_description_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
