# Generated by Django 5.0 on 2024-04-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Against', models.CharField(max_length=100)),
                ('AgaistTeamLogo', models.TextField()),
                ('location', models.CharField(default='Red Bull Arena', max_length=100)),
                ('date', models.DateTimeField()),
                ('type', models.TextField()),
            ],
        ),
    ]
