# Generated by Django 5.0 on 2024-04-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('image', models.URLField(default='https://www.pngitem.com/pimgs/m/146-1468479_my-profile-icon-blank-profile-picture-circle-hd.png')),
                ('TshirtNumber', models.IntegerField(blank=True)),
                ('role', models.CharField(choices=[('GOALKEEPER', 'GoalKeeper'), ('Defense', 'Defense'), ('MIDDLEFEILD', 'MiddleFeild'), ('FORWARD', 'Forward'), ('Trainer', 'Trainer')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='type',
        ),
    ]
