# Generated by Django 5.0 on 2024-04-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_player_remove_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='TshirtNumber',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
