# Generated by Django 5.0 on 2024-04-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_alter_player_tshirtnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('GoalKeeper', 'GoalKeeper'), ('Defense', 'Defense'), ('MiddleFeild', 'MiddleFeild'), ('Forward', 'Forward'), ('Trainer', 'Trainer')], max_length=20),
        ),
    ]
