# Generated by Django 5.0.4 on 2024-04-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_club_staff_fan_club_staff_profile_fanprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club_staff_profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fanprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Club_Staff',
        ),
        migrations.DeleteModel(
            name='Fan',
        ),
        migrations.DeleteModel(
            name='Club_Staff_Profile',
        ),
        migrations.DeleteModel(
            name='FanProfile',
        ),
    ]
